# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3095ac80ea2099437d36b2f229f77583d393fbcbaa9bbbbb2fb16734c656886ac2f9646115670437677c7ec076a391251da42be1d79c0273a9bb733f240a7dc

test:
  secret_key_base: 973ae3d64be294501fb7857eafa49062eb54e19948dd452b56e9b39e0ec007403a830a8de3d613491328ddc369cce5ff656357e5e546b7ed34213c4d581c0102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
